version: '3'

services:
  react-panda-ui:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: react-panda-ui
    container_name: react-panda-ui
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - react-panda-ui
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email lucas.plath@gmail.com --agree-tos --no-eff-email --staging -d react-panda.com  -d www.react-panda.com
  
  volumes:
    certbot-etc:
    certbot-var:
    web-root:
      driver: local
      driver_opts:
        type: none
        device: /usr/src/app/build
        o: bind

  networks:
    app-network:
      driver: bridge