version: '3'

services:
  nodejs:
    ports:
      - "80:80"
    image: docker.pkg.github.com/lucasplath7/react-panda-ui/react-panda-ui-deploy-image:latest
    container_name: react-panda-ui-deploy-image
    restart: unless-stopped
    # command: npm run start
    # networks:
    #   - app-network

  # webserver:
  #   image: nginx:mainline-alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     # - ./build:/usr/share/nginx/html
  #     # - web-root:/usr/share/nginx/html
  #     - web-root:/var/www/html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     # - certbot-etc:/etc/letsencrypt
  #     # - certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - nodejs
  #   command: nginx -g daemon off
  #   networks:
  #     - app-network

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#       - web-root:/usr/share/nginx/html
#     depends_on:
#       - webserver
#     command: certonly --webroot --webroot-path=/usr/share/nginx/html --email lucas.plath@gmail.com --agree-tos --no-eff-email --staging -d react-panda  -d www.react-panda -d react-panda.com

# volumes:
# #   certbot-etc:
# #   certbot-var:
#   web-root:
#     driver: local
#     driver_opts:
#       type: none
#       device: /root
#       o: bind

# networks:
#   app-network:
#     driver: bridge  