FROM node:16.13.1-alpine as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -g cross-env
RUN npm install
COPY . ./
RUN echo "env value: " $REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL
RUN npm run build

# Stage - Production
FROM nginx:1.17-alpine
# COPY ./nginxapp.conf /etc/nginx/conf.d/default.conf
ENV REACT_APP_API_URL $REACT_APP_API_URL
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]