name: build

on:
  push:
    branches: 
      - master

jobs:
  login:
    runs-on: ubuntu-latest
     - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.MY_GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.13
      uses: actions/setup-node@v1
      with:
        node-version: '16.13'
    # - name: Install npm and run unittest
    #   run: |
    #     npm install
    #   env:
    #     CI: true
    # - name: Publish to Github Packages Registry
    #   # uses: isbang/compose-action@v1.4.1
    #   # uses: actions/checkout@v2
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: lucasplath7/react-panda-ui/react-panda-ui-deploy-image
    #     registry: docker.pkg.github.com
    #     username: ${{ secrets.MY_GITHUB_USERNAME }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     # compose-file: docker-compose.yml
    #     run: docker-compose.yml
    #     tags: latest
    - name: Publish to Github Packages Registry
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -f Dockerfile-prod -t docker.pkg.github.com/lucasplath7/react-panda-ui/react-panda-ui-deploy-image:latest .
        docker push docker.pkg.github.com/lucasplath7/react-panda-ui/react-panda-ui-deploy-image:latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        port: ${{ secrets.DO_PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/lucasplath7/react-panda-api/react-panda-api-deploy-image:latest
          docker run -dit -p 5000:5000 docker.pkg.github.com/lucasplath7/react-panda-api/react-panda-api-deploy-image:latest
          docker pull docker.pkg.github.com/lucasplath7/react-panda-ui/react-panda-ui-deploy-image:latest
          docker run -dit -p 80:80 docker.pkg.github.com/lucasplath7/react-panda-ui/react-panda-ui-deploy-image:latest